version: '3.6'
services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: metaverse
      MYSQL_ROOT_PASSWORD: password
  db_pma:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
    - db
    ports:
    - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_USER: root
      PMA_PASSWORD: password
  metaverse:
    depends_on:
    - db
    build: ./.docker
    ports:
    - "8002:9000"
    - "8002:9000/udp"
    - "9000:9000"
    - "9000:9000/udp"
  www:
    depends_on:
    - db
    image: wordpress:latest
    volumes:
    - ".:/var/www/html/wp-content/plugins/opensimulator-bridge"
    ports:
    - 80:80
    - 443:443
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: metaverse
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: 1